[package]
name = "rcu_com"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
nalgebra = "0.33.0"
futures = "0.3.31"
r2r = { version = "0.9" }
eframe = "0.29.1"
env_logger = "0.11.5"
egui_plot = "0.29.0"
egui-modal = "0.5.0"
