name: windows build

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
    release:
        types: [ published ]

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4

            # setup fortran compiler
            - uses: fortran-lang/setup-fortran@v1
              id: setup-fortran
              with:
                compiler: gcc
                version: 13

            # build exe
            - name: build
              run: ${{ env.FC }} cargo build --release --no-default-features
              working-directory: ${{ github.workspace }}
            
            # artifact
            - uses: actions/upload-artifact@v4
              with:
                name: imu-calibration-gui-serialport.exe
                path: ${{ github.workspace }}/target/release/imu_cal_gui.exe