name: windows build

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
    release:
        types: [ published ]

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4

            # setup fortran compiler
            - uses: fortran-lang/setup-fortran@v1
              id: setup-fortran
              with:
                compiler: gcc
                version: 13

            - name: Check Compilers and Versions
              run: |
                echo $env:FC
                cmake --version
                cargo --version

            # build exe
            - name: build
              run: cargo build --release --no-default-features
              working-directory: ${{ github.workspace }}
              env:
                FC: ${{ steps.setup-fortran.outputs.fc }}
            
            # artifact
            - uses: actions/upload-artifact@v4
              with:
                name: imu-calibration-gui-serialport.exe
                path: ${{ github.workspace }}/target/release/imu_cal_gui.exe