name: windows build

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
    release:
        types: [ published ]

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4

            # openblas vcpkg install
            # https://github.com/blas-lapack-rs/openblas-src/blob/master/.github/workflows/openblas-src.yml
            - uses: actions/cache@v2
              with:
                path: ./vcpkg
                key: vcpkg-openblas

            - name: Install vcpkg
              run: |
                git clone https://github.com/Microsoft/vcpkg.git --depth 1
                cd vcpkg
                ./bootstrap-vcpkg.bat

            - name: Install OpenBLAS by vcpkg
              run: |
                ./vcpkg/vcpkg.exe install openblas:${{ matrix.triple }}

            # build exe
            - name: build
              run: cargo build --release --no-default-features
              working-directory: ${{ github.workspace }}
            
            # artifact
            - uses: actions/upload-artifact@v4
              with:
                name: imu-calibration-gui-serialport.exe
                path: ${{ github.workspace }}/target/release/imu_cal_gui.exe